### ISSUE TITLE
cpptoml outright crashes on toml-tests case "invalid/key-empty".

### ISSUE THREAD

**Issue by xorgy** [skystrife/cpptoml#11]
https://github.com/BurntSushi/toml-test/blob/master/tests/invalid/key-empty.toml crashes `parse`.

**Comment by skystrife** [comment]
Thanks for the report. This should be fixed now. I didn't catch it before because the `toml-test` harness just looks for "unsuccessful" program termination, so we were "passing" because we crashed...

I manually ran `./parse` on every invalid file in the test suite to be sure that this wasn't happening for anything else, and it seems that this was the only case where it was.

**Comment by xorgy** [comment]
:+1: :-)
