### ISSUE TITLE
Regression for parsing floats?

### ISSUE THREAD

**Issue by eddelbuettel** [skystrife/cpptoml#27]
I fell a little behind updating [RcppTOML](https://github.com/eddelbuettel/rcpptoml) to the updated cpptoml but just did so.  It turns out that I no longer pass all the regression tests I have, in particular I now fail to parse [this line](https://github.com/eddelbuettel/rcpptoml/blob/master/tests/float.toml#L26) with

```
key2 = 1e1_000
```

at least on my teeny i386 laptop.  

Could this be related to [this commit of yours](https://github.com/skystrife/cpptoml/commit/51d517ccc4b6e1030b15fb5305dd05ccadb94f84) ?

**Comment by eddelbuettel** [comment]
Follow-up: same issue under 64-bit.  Both are Ubuntu systems, one with g++-4.9, the other with g++-5.2.

**Comment by skystrife** [comment]
Yes, this looks to be caused by that referenced commit. However, I think the new behavior might actually be correct, as before it was going to overflow the `double` variable used to store the result.

This is sort of interesting as the example is actually part of the TOML repository's README (where I suspect this test came from), but right below it in the same document is the quote

> 64-bit (double) precision expected.

`1e1000` can't be represented in an IEEE 754 `double`; the following code causes compiler warnings on both gcc and clang on my system:

```cpp
double i = 1e1000;
```

So I think what `cpptoml` is doing here is valid behavior. There's the question of whether or not `long double` values should be supported, perhaps as an extension beyond what TOML itself promises. I don't care too strongly either way, but I have a preference toward not supporting things that aren't actually allowed by the TOML spec.

One of us should probably file a bug upstream about this.

**Comment by eddelbuettel** [comment]
Yes. All those `.toml` files I use are from the spec.  And beforehand we had just one warning / change / difference (related to unicode) so now there are two.  Oh well.

I am OK with your reasoning (esp as we in R-land only have `double` anyway) but it is kinda too bad that we no longer parse that line.  Oh well.

I'll leave you to argue with "your upstream" of the TOML spec :)

**Comment by eddelbuettel** [comment]
Closing this -- RcppTOML 0.0.5 with this behaviour is now on CRAN.
